# permissions for end users to view etcdadmclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcdadmcluster-viewer-role
rules:
- apiGroups:
  - etcdcluster.cluster.x-k8s.io
  resources:
  - etcdadmclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - etcdcluster.cluster.x-k8s.io
  resources:
  - etcdadmclusters/status
  verbs:
  - get
